from enum import Enum

class AuditAction(str, Enum):
    USER_CREATED = "USER_CREATED"
    USER_UPDATED = "USER_UPDATED"
    USER_DELETED = "USER_DELETED"
    USER_SELF_DELETED = "USER_SELF_DELETED"

    LOAN_CREATED = "LOAN_CREATED"
    LOAN_RETURNED = "LOAN_RETURNED"

    TOKEN_REVOKED = "TOKEN_REVOKED"